url: https://elrincondelsanchez.com
lang: es-MX
logo: /assets/img/logo.png
title: El Rincón del Sánchez
theme: jekyll-theme-minimal
description: Awesome Development Projects

github:
  owner_url: https://github.com/isaacsancheza
  owner_name: isaacsancheza
  is_project_page: true
