url: https://elrincondelsanchez.com
lang: es-MX
logo: /assets/img/logo.png
title: El Rincón del Sánchez
theme: jekyll-theme-minimal
description: Awesome Development Projects

github:
  owner_url: https://github.com/isaacsancheza
  owner_username: isaacsancheza
  organization_url: https://github.com/elrincondelsanchez
  organization_username: elrincondelsanchez
