url: https://elrincondelsanchez.com
lang: es-MX
logo: /assets/img/logo.png
title: El Rincón del Sánchez
theme: jekyll-theme-minimal
description: Awesome Development Projects

github:
  is_project_page: true
