logo: /assets/img/logo.png
title: El Rincón del Sánchez
theme: jekyll-theme-minimal

site:
  url: https://elrincondelsanchez.com
  lang: es-MX
  github:
    is_user_page: false
    is_project_page: false
