

theme: jekyll-theme-minimal

site:
  url: https://elrincondelsanchez.com
  logo: /assets/img/logo.png
  lang: es-MX
  title: El Rincón del Sánchez
  github:
    is_user_page: false
    is_project_page: false
